In [ ]:
import numpy as np

In [ ]:
N = 25

N_double_fact = 1
for i in range(N):
    N_double_fact *= i*(i%2 != 0) + 1*(i%2 == 0)

print(N_double_fact)

In [14]:
x = [1, 2, 3, 4, 5, 4]
#x[-1::-2] = [-1, -3, -5]

print(x)

[1, 2, 3, 4, 5, 4]


In [29]:
def cumsum_and_erase(A, erase=1):
    B = [A[0]]
    for i in range(1, len(A)):
        B.append(A[i]+B[i-1])
    B = [i for i in B if i != erase]
    return B

In [43]:
strs = ['thousand devils', 'My name is', 'Room costs']

In [61]:
strs = ['thousand devils', 'My name is', 'Room costs']
strs = ' '.join(strs)
wrds = strs.split()

result = ' '.join(list(filter(lambda x: x.isalpha(), wrds)))

In [59]:
strs.split()

['thousand', 'devils', 'My', 'name', 'is', 'Room', 'costs']

In [49]:
wrds

[['thousand', 'devils'], ['My', 'name', 'is'], ['Room', 'costs']]

In [62]:
result

'thousand devils My name is Room costs'

In [125]:
first = np.random.uniform(0, 10, (3, 3))
second = np.array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [126]:
ret = np.unique(second, return_counts=1)

In [132]:
np.hstack((second, ret[0]))

array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3, 1, 2, 3, 5])

In [147]:
second

array([1, 2, 2, 3, 3, 1, 1, 5, 5, 2, 3, 3])

In [157]:
np.diff(np.diff(second))

array([-1,  1, -1, -2,  2,  4, -4, -3,  4, -1])

In [136]:
from itertools import groupby

In [146]:
np.vstack((np.hstack((second[0], second[1:][np.diff(second)!=0])), ))

array([1, 2, 3, 1, 5, 2, 3])

In [156]:
for i, j in groupby(second):
    print(i, list(j))

1 [1]
2 [2, 2]
3 [3, 3]
1 [1, 1]
5 [5, 5]
2 [2]
3 [3, 3]
